export const BESTSELLER_PRODUCTS = "BESTSELLER_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const SET_SEARCH_PRODUCTS = "SET_SEARCH_PRODUCTS";
export const SET_BESTSELLER_PRODUCTS = "SET_BESTSELLER_PRODUCTS";
export const SIGNUP_USER = "SIGNUP_USER";
export const LOGIN_USER = "LOGIN_USER";
export const UPDATE_USER = "UPDATE_USER";
export const SET_SIGNUP_USER = "SET_SIGNUP_USER";